"""settings, company rules

Revision ID: 0352563b66f9
Revises: fa4f12e7140d
Create Date: 2026-10-03 14:13:11.301281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0352563b66f9'
down_revision: Union[str, Sequence[str], None] = 'fa4f12e7140d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_above_amount', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('auto_post', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('auto_post')
        batch_op.drop_column('review_above_amount')

    op.drop_table('app_settings')
    # ### end Alembic commands ###
