"""session version, longer audit entity ids

Revision ID: 269ce8692a6f
Revises: 0352563b66f9
Create Date: 2026-10-03 15:29:46.535149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269ce8692a6f'
down_revision: Union[str, Sequence[str], None] = '0352563b66f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The rebuild must keep AUTOINCREMENT, or audit ids could be reused (see 41534f2133cd).
    with op.batch_alter_table(
        'audit_events', schema=None, table_kwargs={'sqlite_autoincrement': True}
    ) as batch_op:
        batch_op.alter_column('entity_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table(
        'users', schema=None, table_kwargs={'sqlite_autoincrement': True}
    ) as batch_op:
        batch_op.add_column(sa.Column('session_version', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'users', schema=None, table_kwargs={'sqlite_autoincrement': True}
    ) as batch_op:
        batch_op.drop_column('session_version')

    # The rebuild must keep AUTOINCREMENT, or audit ids could be reused (see 41534f2133cd).
    with op.batch_alter_table(
        'audit_events', schema=None, table_kwargs={'sqlite_autoincrement': True}
    ) as batch_op:
        batch_op.alter_column('entity_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
