"""vouchers and ledger mappings

Revision ID: fa4f12e7140d
Revises: 41534f2133cd
Create Date: 2026-10-02 21:26:22.807693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4f12e7140d'
down_revision: Union[str, Sequence[str], None] = '41534f2133cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('party_ledger', sa.String(length=255), nullable=False),
    sa.Column('item_ledger', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'party_ledger')
    )
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('voucher_uid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('extraction', sa.JSON(), nullable=True),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('invoice', sa.JSON(), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=False),
    sa.Column('accounting', sa.JSON(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('party_name', sa.String(length=255), nullable=True),
    sa.Column('party_gstin', sa.String(length=15), nullable=True),
    sa.Column('voucher_kind', sa.String(length=20), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('post_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id'),
    sa.UniqueConstraint('voucher_uid'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.create_index('ix_vouchers_company_invoice', ['company_id', 'invoice_number'], unique=False)
        batch_op.create_index('ix_vouchers_company_status', ['company_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_index('ix_vouchers_company_status')
        batch_op.drop_index('ix_vouchers_company_invoice')

    op.drop_table('vouchers')
    op.drop_table('ledger_mappings')
    # ### end Alembic commands ###
